# Generated by Django 4.2.3 on 2023-07-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('habitat', models.CharField(max_length=100)),
                ('us_canada_population_estimate', models.IntegerField()),
                ('population_trend', models.CharField(max_length=100)),
            ],
        ),
    ]
