# Generated by Django 4.2.3 on 2023-07-12 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_finch_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finch',
            name='age',
        ),
    ]
